### ISSUE TITLE
Original images are not used in re-training decoder?

### ISSUE THREAD

**Issue by gdjmck** [vinojjayasundara/textcaps#1]
According to the paper, it says that the original images and sharpened reconstructed images are combined and used as new training set for decoder retraining.
But in your code only the sharpened reconstructed images are used as re-train dataset, was it out of actual experiment purpose to leave the original images out?

**Comment by vinojjayasundara** [comment]
> According to the paper, it says that the original images and sharpened reconstructed images are combined and used as new training set for decoder retraining.
> But in your code only the sharpened reconstructed images are used as re-train dataset, was it out of actual experiment purpose to leave the original images out?

Thank you for the query. Combining original images and sharpened reconstructed images achieves faster convergence in re-training due to the increased training set size. Other than that, it does not affect the results much. Therefore, you can choose to use either the combined set or the sharpened images set for re-training. We are currently improving the code for the journal version of the paper, and we decided to use only the sharpened images set for simplicity.
